-- =========================================================
-- ESQUEMA DE BANCO DE DADOS (SUPABASE / POSTGRESQL)
-- =========================================================
-- Execute este arquivo no SQL Editor do seu projeto Supabase
-- quando decidir migrar do LocalStorage para a Nuvem.

-- 1. TABELA DE PERFIS DE USUÁRIO (Vinculada ao auth.users do Supabase)
CREATE TABLE public.profiles (
  id UUID REFERENCES auth.users(id) PRIMARY KEY,
  name TEXT NOT NULL,
  role TEXT CHECK (role IN ('admin', 'funcionario')) DEFAULT 'funcionario',
  created_at TIMESTAMPTZ DEFAULT NOW()
);
-- Habilita RLS (Row Level Security)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- 2. TABELA DE PRODUTOS
CREATE TABLE public.produtos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  categoria TEXT NOT NULL,
  operacao TEXT CHECK (operacao IN ('Espetinho', 'Bebidas')),
  unidade TEXT DEFAULT 'un',
  custo NUMERIC(10, 2) NOT NULL DEFAULT 0,
  preco NUMERIC(10, 2) NOT NULL DEFAULT 0,
  estoque INTEGER NOT NULL DEFAULT 0,
  estoque_min INTEGER NOT NULL DEFAULT 5,
  status TEXT CHECK (status IN ('ativo', 'inativo')) DEFAULT 'ativo',
  tipo TEXT CHECK (tipo IN ('produzido', 'pronto')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.produtos ENABLE ROW LEVEL SECURITY;

-- 3. TABELA DE VENDAS
CREATE TABLE public.vendas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  data DATE NOT NULL DEFAULT CURRENT_DATE,
  tipo TEXT NOT NULL, -- Mesa, Balcão, Delivery, etc.
  pagamento TEXT NOT NULL, -- Pix, Dinheiro, Cartão...
  obs TEXT,
  total NUMERIC(10, 2) NOT NULL DEFAULT 0,
  custo_total NUMERIC(10, 2) NOT NULL DEFAULT 0,
  vendedor_id UUID REFERENCES public.profiles(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.vendas ENABLE ROW LEVEL SECURITY;

-- 4. TABELA DE ITENS DA VENDA
CREATE TABLE public.venda_itens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venda_id BIGINT REFERENCES public.vendas(id) ON DELETE CASCADE,
  produto_id BIGINT REFERENCES public.produtos(id),
  qtd INTEGER NOT NULL,
  preco_unitario NUMERIC(10, 2) NOT NULL,
  custo_unitario NUMERIC(10, 2) NOT NULL,
  subtotal NUMERIC(10, 2) NOT NULL
);
ALTER TABLE public.venda_itens ENABLE ROW LEVEL SECURITY;

-- 5. TABELA DE PRODUÇÃO INTERNA
CREATE TABLE public.producoes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  produto_id BIGINT REFERENCES public.produtos(id),
  qtd INTEGER NOT NULL,
  obs TEXT,
  usuario_id UUID REFERENCES public.profiles(id),
  data DATE NOT NULL DEFAULT CURRENT_DATE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.producoes ENABLE ROW LEVEL SECURITY;

-- 6. TABELA DE CONSUMO INTERNO / PERDAS
CREATE TABLE public.consumos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  produto_id BIGINT REFERENCES public.produtos(id),
  qtd INTEGER NOT NULL,
  motivo TEXT NOT NULL, -- Ex: Quebra, Perda, Consumo, Cortesia
  obs TEXT,
  usuario_id UUID REFERENCES public.profiles(id),
  data DATE NOT NULL DEFAULT CURRENT_DATE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.consumos ENABLE ROW LEVEL SECURITY;

-- 7. TABELA DE COMPRAS
CREATE TABLE public.compras (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fornecedor TEXT NOT NULL,
  data DATE NOT NULL DEFAULT CURRENT_DATE,
  operacao TEXT CHECK (operacao IN ('Espetinho', 'Bebidas')),
  pagamento TEXT NOT NULL,
  obs TEXT,
  total NUMERIC(10, 2) NOT NULL DEFAULT 0,
  usuario_id UUID REFERENCES public.profiles(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.compras ENABLE ROW LEVEL SECURITY;

-- 8. TABELA DE ITENS DA COMPRA
CREATE TABLE public.compra_itens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  compra_id BIGINT REFERENCES public.compras(id) ON DELETE CASCADE,
  produto_id BIGINT REFERENCES public.produtos(id),
  qtd INTEGER NOT NULL,
  custo_unitario NUMERIC(10, 2) NOT NULL,
  total NUMERIC(10, 2) NOT NULL
);
ALTER TABLE public.compra_itens ENABLE ROW LEVEL SECURITY;

-- 9. TABELA DE AUDITORIA (LOGS)
CREATE TABLE public.auditoria (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id UUID REFERENCES public.profiles(id),
  acao TEXT NOT NULL,
  detalhes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.auditoria ENABLE ROW LEVEL SECURITY;

-- ==========================================
-- POLÍTICAS DE SEGURANÇA (RLS BÁSICAS)
-- ==========================================
-- (Exemplo: Funcionários podem ler produtos e inserir vendas, 
-- mas apenas admin pode deletar ou editar custos de produtos antigos)

-- Permitir leitura de dados a todos os usuários autenticados
CREATE POLICY "Permitir leitura para autenticados" ON public.produtos FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Permitir leitura para autenticados" ON public.vendas FOR SELECT USING (auth.role() = 'authenticated');

-- ==========================================
-- FUNCTION PARA BAIXAR ESTOQUE (CONCORRÊNCIA SEGURA) 
-- ==========================================
-- Uma transação que previne que 2 pessoas baixem o estoque na mesma fração de segundo
CREATE OR REPLACE FUNCTION baixar_estoque(p_produto_id BIGINT, p_qtd INTEGER)
RETURNS void AS $$
BEGIN
  UPDATE public.produtos
  SET estoque = estoque - p_qtd
  WHERE id = p_produto_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
